
const truth = {
  normal: [
  "What's the most embarrassing thing you've ever done?",
  "Have you ever had a crush on someone here?",
  "What's your biggest secret?",
  "What's your guilty pleasure?",
  "Have you ever lied to get out of trouble?",
  "What is something you've done that you regret deeply?",
  "Have you ever lied to your best friend? What about?",
  "What secret are you keeping from your parents?",
  "Who is someone you pretend to like but secretly don't?",
  "What was your most awkward date experience?",
  "Have you ever blamed someone else for your mistake?",
  "What is the most selfish thing you've ever done?",
  "What’s the one thing you’re most ashamed of?",
  "Who do you stalk on social media the most?",
  "What's the weirdest thing you’ve done alone?",
  "Have you ever cheated on a test or assignment?",
  "What's the worst lie you've ever told?",
  "What’s your biggest insecurity?",
  "Have you ever broken someone's trust?",
  "Have you ever had a crush on a teacher or mentor?",
  "What’s a secret you've never told anyone?",
  "What's your guilty pleasure TV show?",
  "Have you ever pretended to be sick to skip something important?",
  "Have you ever eavesdropped on someone?",
  "What’s something you’re glad your parents don’t know about you?",
  "Have you ever made fun of someone behind their back?",
  "What’s the biggest mistake you've made in a relationship?",
  "Have you ever sent a message to the wrong person?",
  "Have you ever told a secret you promised to keep?",
  "What rumor did you help spread — and regret?",
  "Have you ever lied in this game?",
  "What's the most childish thing you still do?",
  "What’s a habit you’re too embarrassed to admit?",
  "Have you ever had a crush on a friend's partner?",
  "Have you ever ghosted someone? Why?",
  "What’s a secret talent no one knows about?",
  "What’s the meanest thing you’ve ever said to someone?",
  "Who in this room do you think is most attractive?",
  "What’s the last thing you searched on your phone?",
  "Have you ever been caught doing something you shouldn’t have?",
  "What’s your weirdest dream ever?",
  "If you could delete one memory, what would it be?",
  "Have you ever stolen something (even small)?",
  "What’s the worst thing you’ve said to your parents?",
  "Have you ever flirted just to get something you wanted?",
  "What’s the cringiest message you've ever sent?",
  "If your life were a movie, what would it be rated and why?",
  "Have you ever faked being happy when you weren't?",
  "Have you ever had a dream about someone in this room?",
  "What would you do if you were invisible for one day?",
  "What’s the most ridiculous thing you’ve ever cried about?",
  "Have you ever laughed at something you shouldn’t have?",
  "What’s the most awkward thing you’ve said to a crush?",
  "Have you ever kept a diary or journal? What’s in it?",
  "What’s the worst gift you’ve ever received?",
  "Have you ever lied about your age? Why?",
  "What’s the most embarrassing thing in your room right now?",
  "Have you ever had a crush on someone you barely knew?",
  "What’s the weirdest food combo you’ve ever tried?",
  "Have you ever pretended to know something you didn’t?",
  "What’s the most trouble you’ve gotten into at school?",
  "Have you ever had an imaginary friend? Describe them.",
  "What’s the most awkward thing you’ve done in public?",
  "Have you ever lied to impress someone? What was it?",
  "What’s the most embarrassing thing you’ve worn?",
  "Have you ever forgotten someone’s name after meeting them?",
  "What’s the silliest thing you’ve argued about?",
  "Have you ever lied about liking a gift?",
  "What’s the most embarrassing song on your playlist?",
  "Have you ever walked into something because you were distracted?",
  "What’s the worst thing you’ve done to avoid a boring event?",
  "Have you ever accidentally broken something and not told anyone?",
  "What’s the most embarrassing nickname you’ve ever had?",
  "Have you ever tried to impress someone and failed miserably?",
  "What’s the weirdest thing you’ve Googled?",
  "Have you ever lied about being good at something?",
  "What’s the most awkward family moment you’ve experienced?",
  "Have you ever had a crush you were too shy to tell?",
  "What’s the worst food you’ve ever eaten?",
  "Have you ever sung karaoke? What song?",
  "What’s the most embarrassing thing you’ve posted online?",
  "Have you ever lied to a teacher? What about?",
  "What’s the weirdest habit you had as a kid?",
  "Have you ever gotten lost somewhere embarrassing?",
  "What’s the most ridiculous thing you’ve believed?",
  "Have you ever tripped or fallen in front of a crowd?",
  "What’s the worst date you’ve ever been on?",
  "Have you ever lied about your feelings for someone?",
  "What’s the most awkward thing you’ve overheard?",
  "Have you ever had a wardrobe malfunction?",
  "What’s the silliest thing you’ve done to get attention?",
  "Have you ever lied to avoid hurting someone’s feelings?",
  "What’s the most embarrassing thing you’ve done for love?",
  "Have you ever had a crush on a celebrity? Who?",
  "What’s the weirdest thing you’ve done to avoid someone?",
  "Have you ever forgotten an important date or event?",
  "What’s the most embarrassing thing you’ve said in a group?",
  "Have you ever lied about where you were?",
  "What’s the worst haircut you’ve ever had?",
  "Have you ever been caught singing or dancing alone?",
  "What’s the most awkward thing you’ve done at a party?",
  "Have you ever lied about your hobbies to seem cool?",
  "What’s the most embarrassing thing you’ve done in front of a crush?",
  "Have you ever had a secret you told only one person?",
  "What’s the weirdest thing you’ve done to stay awake?",
  "Have you ever laughed at the wrong moment?",
  "What’s the most embarrassing thing you’ve done to fit in?",
  "Have you ever lied about a skill you don’t have?",
  "What’s the worst thing you’ve done out of boredom?",
  "Have you ever had a crush on someone older or younger?",
  "What’s the most awkward photo of you that exists?",
  "Have you ever lied to get out of a date?",
  "What’s the silliest thing you’ve done to avoid a fight?",
  "Have you ever accidentally called someone the wrong name?",
  "What’s the most embarrassing thing you’ve done at work?",
  "Have you ever lied about liking a movie or book?",
  "What’s the weirdest thing you’ve done in a bathroom?",
  "Have you ever been caught talking to yourself?",
  "What’s the most embarrassing thing you’ve done on a video call?",
  "Have you ever lied to get out of a family event?",
  "What’s the silliest thing you’ve done to cheer someone up?",
  "Have you ever had a crush you knew was impossible?",
  "What’s the most awkward thing you’ve done in a classroom?",
  "Have you ever lied about your plans to avoid someone?",
  "What’s the weirdest thing you’ve done to impress a friend?",
  "Have you ever been caught in a lie? What happened?",
  "What’s the most embarrassing thing you’ve done for a dare?",
  "Have you ever lied about knowing someone famous?",
  "What’s the silliest thing you’ve done when drunk?",
  "Have you ever had a crush on a fictional character?",
  "What’s the most awkward thing you’ve said to a stranger?",
  "Have you ever lied about your job or accomplishments?",
  "What’s the weirdest thing you’ve done to avoid chores?",
  "Have you ever been embarrassed by something your family did?",
  "What’s the most ridiculous thing you’ve done for a bet?",
  "Have you ever lied to avoid embarrassment?",
  "What’s the most awkward thing you’ve done to get revenge?",
  "Have you ever had a crush on someone you worked with?",
  "What’s the weirdest thing you’ve done to stay warm?",
  "Have you ever lied about your favorite food?",
  "What’s the most embarrassing thing you’ve done in a store?",
  "Have you ever been caught daydreaming about something weird?",
  "What’s the silliest thing you’ve done to avoid a call?",
  "Have you ever lied about being busy to avoid plans?",
  "What’s the most awkward thing you’ve done at a family reunion?",
  "Have you ever had a crush on someone you met online?",
  "What’s the weirdest thing you’ve done to get free stuff?",
  "Have you ever lied about your relationship status?",
  "What’s the most embarrassing thing you’ve done at a concert?",
  "Have you ever been caught doing something silly by a parent?",
  "What’s the silliest thing you’ve done to avoid homework?",
  "Have you ever lied about your location to someone?",
  "What’s the most awkward thing you’ve done in a restaurant?",
  "Have you ever had a crush on a neighbor?",
  "What’s the weirdest thing you’ve done to stay cool in the heat?",
  "Have you ever lied about liking someone’s outfit?",
  "What’s the most embarrassing thing you’ve done on a trip?",
  "Have you ever been caught gossiping about someone?",
  "What’s the silliest thing you’ve done to win a game?",
  "Have you ever lied about your plans for the weekend?",
  "What’s the most awkward thing you’ve done at a wedding?",
  "Have you ever had a crush on a friend’s sibling?",
  "What’s the weirdest thing you’ve done to avoid a meeting?",
  "Have you ever lied about your favorite song?",
  "What’s the most embarrassing thing you’ve done in a car?",
  "Have you ever been caught making a funny face?",
  "What’s the silliest thing you’ve done to get out of trouble?",
  "Have you ever lied about being good at a sport?",
  "What’s the most awkward thing you’ve done in a movie theater?",
  "Have you ever had a crush on someone you saw only once?",
  "What’s the weirdest thing you’ve done to avoid cleaning?",
  "Have you ever lied about your favorite color?",
  "What’s the most embarrassing thing you’ve done at a park?",
  "Have you ever been caught pretending to be someone else?",
  "What’s the silliest thing you’ve done to make someone laugh?",
  "Have you ever lied about your birthday?",
  "What’s the most awkward thing you’ve done at a sleepover?",
  "Have you ever had a crush on someone in a different city?",
  "What’s the weirdest thing you’ve done to avoid a party?",
  "Have you ever lied about liking a present?",
  "What’s the most embarrassing thing you’ve done at a mall?",
  "Have you ever been caught singing in the shower?",
  "What’s the silliest thing you’ve done to avoid a test?",
  "Have you ever lied about your favorite animal?",
  "What’s the most awkward thing you’ve done at a gym?",
  "Have you ever had a crush on someone you didn’t expect?",
  "What’s the weirdest thing you’ve done to avoid a conversation?",
  "Have you ever lied about your favorite book?",
  "What’s the most embarrassing thing you’ve done at a beach?",
  "Have you ever been caught dancing alone?",
  "What’s the silliest thing you’ve done to avoid a chore?",
  "Have you ever lied about your favorite movie?",
  "What’s the most awkward thing you’ve done at a library?",
  "Have you ever had a crush on someone from a show or movie?",
  "What’s the weirdest thing you’ve done to avoid a date?",
  "Have you ever lied about your favorite hobby?",
  "What’s the most embarrassing thing you’ve done at a zoo?",
  "Have you ever been caught talking about someone nearby?",
  "What’s the silliest thing you’ve done to avoid a gift exchange?",
  "Have you ever lied about your favorite place to visit?",
  "What’s the most awkward thing you’ve done at a friend’s house?",
  "Have you ever had a crush on someone you met at a party?",
  "What’s the weirdest thing you’ve done to avoid a family photo?",
  "Have you ever lied about your favorite sport?",
  "What’s the most embarrassing thing you’ve done at a festival?",
  "Have you ever been caught making up a story?",
  "What’s the silliest thing you’ve done to avoid a group chat?",
  "Have you ever lied about your favorite band?",
  "What’s the most awkward thing you’ve done at a club?",
  "Have you ever had a crush on someone in a different country?",
  "What’s the weirdest thing you’ve done to avoid a reunion?",
  "Have you ever lied about your favorite TV show?",
  "What’s the most embarrassing thing you’ve done at a pool?",
  "Have you ever been caught pretending to be sick?",
  "What’s the silliest thing you’ve done to avoid a sleepover?",
  "Have you ever lied about your favorite game?",
  "What’s the most awkward thing you’ve done at a coffee shop?",
  "Have you ever had a crush on someone you saw on social media?",
  "What’s the weirdest thing you’ve done to avoid a workout?",
  "Have you ever lied about your favorite food combo?",
  "What’s the most embarrassing thing you’ve done at a museum?",
  "Have you ever been caught laughing at your own joke?",
  "What’s the silliest thing you’ve done to avoid a meeting?",
  "Have you ever lied about your favorite season?",
  "What’s the most awkward thing you’ve done at a concert?",
  "Have you ever had a crush on someone you met at school?",
  "What’s the weirdest thing you’ve done to avoid a call?",
  "Have you ever lied about your favorite drink?",
  "What’s the most embarrassing thing you’ve done at a theme park?",
  "Have you ever been caught making a weird face in a photo?",
  "What’s the silliest thing you’ve done to avoid a presentation?",
  "Have you ever lied about your favorite place to eat?",
  "What’s the most awkward thing you’ve done at a grocery store?",
  "Have you ever had a crush on someone you met at work?",
  "What’s the weirdest thing you’ve done to avoid a family dinner?",
  "Have you ever lied about your favorite dessert?",
  "What’s the most embarrassing thing you’ve done at a sporting event?",
  "Have you ever been caught pretending to know a song?",
  "What’s the silliest thing you’ve done to avoid a trip?",
  "Have you ever lied about your favorite activity?",
  "What’s the most awkward thing you’ve done at a public event?",
  "Have you ever had a crush on someone you met randomly?",
  "What’s the weirdest thing you’ve done to avoid a text?",
  "Have you ever lied about your favorite holiday?",
  "What’s the most embarrassing thing you’ve done at a fair?",
  "Have you ever been caught pretending to be busy?",
  "What’s the silliest thing you’ve done to avoid a game night?",
  "Have you ever lied about your favorite ice cream flavor?",
  "What’s the most awkward thing you’ve done at a family gathering?",
  "Have you ever had a crush on someone you met through a friend?",
  "What’s the weirdest thing you’ve done to avoid a social event?",
  "Have you ever lied about your favorite type of music?",
  "What’s the most embarrassing thing you’ve done at a barbecue?",
  "Have you ever been caught pretending to like something?",
  "What’s the silliest thing you’ve done to avoid a party?",
  "Have you ever lied about your favorite snack?",
  "What’s the most awkward thing you’ve done at a public restroom?",
  "Have you ever had a crush on someone you met on vacation?",
  "What’s the weirdest thing you’ve done to avoid a group outing?",
  "Have you ever lied about your favorite candy?",
  "What’s the most embarrassing thing you’ve done at a school event?",
  "Have you ever been caught pretending to be someone you’re not?",
  "What’s the silliest thing you’ve done to avoid a conversation?",
  "Have you ever lied about your favorite fruit?",
  "What’s the most awkward thing you’ve done at a picnic?",
  "Have you ever had a crush on someone you met at a concert?",
  "What’s the weirdest thing you’ve done to avoid a family trip?",
  "Have you ever lied about your favorite color to fit in?",
  "What’s the most embarrassing thing you’ve done at a carnival?",
  "Have you ever been caught pretending to know a fact?",
  "What’s the silliest thing you’ve done to avoid a date night?",
  "Have you ever lied about your favorite vegetable?",
  "What’s the most awkward thing you’ve done at a friend’s party?",
  "Have you ever had a crush on someone you met at a game?",
  "What’s the weirdest thing you’ve done to avoid a video call?",
  "Have you ever lied about your favorite scent?",
  "What’s the most embarrassing thing you’ve done at a public pool?",
  "Have you ever been caught pretending to be happy?",
  "What’s the silliest thing you’ve done to avoid a family event?",
  "Have you ever lied about your favorite flower?",
  "What’s the most awkward thing you’ve done at a team event?",
  "Have you ever had a crush on someone you met at a festival?",
  "What’s the weirdest thing you’ve done to avoid a reunion?",
  "Have you ever lied about your favorite weather?",
  "What’s the most embarrassing thing you’ve done at a holiday party?",
  "Have you ever been caught pretending to be confident?",
  "What’s the silliest thing you’ve done to avoid a sleepover?",
  "Have you ever lied about your favorite quote?",
  "What’s the most awkward thing you’ve done at a community event?",
  "Have you ever had a crush on someone you met at a club?",
  "What’s the weirdest thing you’ve done to avoid a group chat?",
  "Have you ever lied about your favorite place to relax?",
  "What’s the most embarrassing thing you’ve done at a dance?",
  "Have you ever been caught pretending to be interested?",
  "What’s the silliest thing you’ve done to avoid a workout?",
  "Have you ever lied about your favorite smell?",
  "What’s the most awkward thing you’ve done at a book club?",
  "Have you ever had a crush on someone you met at a park?",
  "What’s the weirdest thing you’ve done to avoid a game?",
  "Have you ever lied about your favorite day of the week?",
  "What’s the most embarrassing thing you’ve done at a talent show?"
],


party: [
    "What's the dumbest thing you've done at a party?",
    "Have you ever danced on a table?",
    "What's the most embarrassing song you've sung at karaoke during a party?",
    "Have you ever spilled a drink on someone at a party?",
    "What's the weirdest food combo you’ve tried at a party?",
    "Have you ever crashed a party you weren’t invited to?",
    "What’s the best party theme you’ve ever experienced?",
    "Have you ever gotten lost trying to find a party?",
    "What’s the most epic party game you’ve played?",
    "Have you ever fallen asleep at a party?",
    "What’s the funniest costume you’ve worn to a party?",
    "Have you ever accidentally broken something at a party?",
    "What’s the most memorable party you’ve ever been to?",
    "Have you ever been kicked out of a party?",
    "What’s the worst party food you’ve ever tasted?",
    "Have you ever stayed at a party until sunrise?",
    "What’s the best party favor you’ve ever received?",
    "Have you ever lost something valuable at a party?",
    "What’s the most awkward dance move you’ve tried at a party?",
    "Have you ever been part of a party prank?",
    "What’s the strangest drink you’ve tried at a party?",
    "Have you ever forgotten someone’s name at a party?",
    "What’s the best party you’ve ever thrown?",
    "Have you ever gotten into an argument at a party?",
    "What’s the most unexpected thing that happened at a party you attended?",
    "Have you ever sung in front of everyone at a party?",
    "What’s the worst outfit you’ve worn to a party?",
    "Have you ever been the designated driver for a party?",
    "What’s the most fun party activity you’ve done?",
    "Have you ever tripped or fallen at a party?",
    "What’s the best party playlist you’ve heard?",
    "Have you ever been stuck at a boring party?",
    "What’s the most creative party decoration you’ve seen?",
    "Have you ever been part of a surprise party?",
    "What’s the worst party you’ve ever attended?",
    "Have you ever danced with a stranger at a party?",
    "What’s the funniest party story you’ve heard?",
    "Have you ever lost your shoes at a party?",
    "What’s the best party snack you’ve ever had?",
    "Have you ever been to a party with a crazy dress code?",
    "What’s the most embarrassing thing you’ve said at a party?",
    "Have you ever helped clean up after a party?",
    "What’s the wildest party location you’ve been to?",
    "Have you ever been to a party where the police showed up?",
    "What’s the best party drink you’ve ever tried?",
    "Have you ever gotten sick at a party?",
    "What’s the most memorable party speech you’ve heard?",
    "Have you ever been to a costume party where you didn’t dress up?",
    "What’s the funniest thing you’ve seen someone do at a party?",
    "Have you ever been to a party with a live band?",
    "What’s the best party gift you’ve given someone?",
    "Have you ever been locked out of a party?",
    "What’s the most over-the-top party you’ve attended?",
    "Have you ever played a drinking game at a party?",
    "What’s the weirdest party tradition you’ve encountered?",
    "Have you ever been to a party where you didn’t know anyone?",
    "What’s the best dance-off you’ve seen at a party?",
    "Have you ever brought an unexpected guest to a party?",
    "What’s the most ridiculous party rule you’ve followed?",
    "Have you ever been to a party with a photo booth?",
    "What’s the most awkward moment you’ve had at a party?",
    "Have you ever been part of a party flash mob?",
    "What’s the best party you’ve been to in another country?",
    "Have you ever forgotten where you parked at a party?",
    "What’s the most creative party invitation you’ve received?",
    "Have you ever been to a party with a secret theme?",
    "What’s the funniest party foul you’ve witnessed?",
    "Have you ever been to a pool party?",
    "What’s the best party you’ve been to with family?",
    "Have you ever been to a party that got out of control?",
    "What’s the most unique party venue you’ve seen?",
    "Have you ever been to a party with a piñata?",
    "What’s the best party you’ve attended for a holiday?",
    "Have you ever been to a party where you won a prize?",
    "What’s the most memorable party conversation you’ve had?",
    "Have you ever been to a silent disco party?",
    "What’s the best party you’ve been to with coworkers?",
    "Have you ever been to a party with a magician?",
    "What’s the worst party game you’ve played?",
    "Have you ever been to a party with a live animal?",
    "What’s the best party you’ve been to for a birthday?",
    "Have you ever been to a party where you got lost inside?",
    "What’s the most epic party entrance you’ve made?",
    "Have you ever been to a party with a celebrity?",
    "What’s the best party you’ve been to in a small town?",
    "Have you ever been to a themed dinner party?",
    "What’s the funniest thing you’ve overheard at a party?",
    "Have you ever been to a party with fireworks?",
    "What’s the best party you’ve been to on a beach?",
    "Have you ever been to a party with a bounce house?",
    "What’s the most awkward party gift you’ve received?",
    "Have you ever been to a party where you didn’t speak the language?",
    "What’s the best party you’ve been to in the winter?",
    "Have you ever been to a party with a talent show?",
    "What’s the most surprising party guest you’ve met?",
    "Have you ever been to a party with a scavenger hunt?",
    "What’s the best party you’ve been to on a rooftop?",
    "Have you ever been to a party where you got a makeover?",
    "What’s the funniest party photo you’ve been in?",
    "Have you ever been to a party with a DJ?",
    "What’s the best party you’ve been to for New Year’s?",
    "Have you ever been to a party with a costume contest?",
    "What’s the most memorable party fight you’ve seen?",
    "Have you ever been to a party with a karaoke machine?",
    "What’s the best party you’ve been to in a big city?",
    "Have you ever been to a party with a food truck?",
    "What’s the most epic party speech you’ve given?",
    "Have you ever been to a party with a mechanical bull?",
    "What’s the best party you’ve been to for Halloween?",
    "Have you ever been to a party where you stayed too long?",
    "What’s the most creative party drink you’ve made?",
    "Have you ever been to a party with a live painter?",
    "What’s the best party you’ve been to on a boat?",
    "Have you ever been to a party with a trivia game?",
    "What’s the most awkward party dance you’ve seen?",
    "Have you ever been to a party with a petting zoo?",
    "What’s the best party you’ve been to for a wedding?",
    "Have you ever been to a party with a fortune teller?",
    "What’s the most epic party exit you’ve made?",
    "Have you ever been to a party with a laser light show?",
    "What’s the best party you’ve been to in a park?",
    "Have you ever been to a party with a silent auction?",
    "What’s the most memorable party toast you’ve heard?",
    "Have you ever been to a party with a themed cocktail?",
    "What’s the best party you’ve been to for a graduation?",
    "Have you ever been to a party with a live comedian?",
    "What’s the most unexpected party location you’ve been to?",
    "Have you ever been to a party with a water slide?",
    "What’s the best party you’ve been to in a forest?",
    "Have you ever been to a party with a dance instructor?",
    "What’s the most epic party game win you’ve had?",
    "Have you ever been to a party with a balloon artist?",
    "What’s the best party you’ve been to for a baby shower?",
    "Have you ever been to a party with a live orchestra?",
    "What’s the most memorable party you’ve planned?",
    "Have you ever been to a party with a themed photo booth?",
    "What’s the best party you’ve been to in a museum?",
    "Have you ever been to a party with a hypnotist?",
    "What’s the most epic party you’ve been to in a castle?",
    "Have you ever been to a party with a juggler?",
    "What’s the best party you’ve been to for a promotion?",
    "Have you ever been to a party with a virtual reality setup?",
    "What’s the most memorable party you’ve been to in a hotel?",
    "Have you ever been to a party with a fire dancer?",
    "What’s the best party you’ve been to for an anniversary?",
    "Have you ever been to a party with a face painter?",
    "What’s the most epic party you’ve been to in a barn?",
    "Have you ever been to a party with a live tattoo artist?",
    "What’s the best party you’ve been to for a retirement?",
    "Have you ever been to a party with a live chef demo?",
    "What’s the most memorable party you’ve been to in a club?",
    "Have you ever been to a party with a drone show?",
    "What’s the best party you’ve been to for a housewarming?",
    "Have you ever been to a party with a live ice sculptor?",
    "What’s the most epic party you’ve been to in a mansion?",
    "Have you ever been to a party with a live psychic?",
    "What’s the best party you’ve been to for a reunion?",
    "Have you ever been to a party with a live graffiti artist?",
    "What’s the most memorable party you’ve been to in a loft?",
    "Have you ever been to a party with a live caricature artist?",
    "What’s the best party you’ve been to for a charity event?",
    "Have you ever been to a party with a live acrobat?",
    "What’s the most epic party you’ve been to in a vineyard?",
    "Have you ever been to a party with a live puppeteer?",
    "What’s the best party you’ve been to for a book launch?",
    "Have you ever been to a party with a live magician?",
    "What’s the most memorable party you’ve been to in a theater?",
    "Have you ever been to a party with a live storyteller?",
    "What’s the best party you’ve been to for a product launch?",
    "Have you ever been to a party with a live fire show?",
    "What’s the most epic party you’ve been to in a garden?",
    "Have you ever been to a party with a live escape room?",
    "What’s the best party you’ve been to for a cultural event?",
    "Have you ever been to a party with a live poet?",
    "What’s the most memorable party you’ve been to in a stadium?",
    "Have you ever been to a party with a live sword swallower?",
    "What’s the best party you’ve been to for a festival?",
    "Have you ever been to a party with a live contortionist?",
    "What’s the most epic party you’ve been to in a desert?",
    "Have you ever been to a party with a live ventriloquist?",
    "What’s the best party you’ve been to for a sports event?",
    "Have you ever been to a party with a live mentalist?",
    "What’s the most memorable party you’ve been to in a zoo?",
    "Have you ever been to a party with a live opera singer?",
    "What’s the best party you’ve been to for a film premiere?",
    "Have you ever been to a party with a live balloon sculptor?",
    "What’s the most epic party you’ve been to in a cave?",
    "Have you ever been to a party with a live juggler?",
    "What’s the best party you’ve been to for a music release?",
    "Have you ever been to a party with a live hypnotist?",
    "What’s the most memorable party you’ve been to in a library?",
    "Have you ever been to a party with a live fire breather?",
    "What’s the best party you’ve been to for a fashion show?",
    "Have you ever been to a party with a live stilt walker?",
    "What’s the most epic party you’ve been to in a mountain?",
    "Have you ever been to a party with a live mime?",
    "What’s the best party you’ve been to for an art exhibit?",
    "Have you ever been to a party with a live breakdancer?",
    "What’s the most memorable party you’ve been to in a church?",
    "Have you ever been to a party with a live choir?",
    "What’s the best party you’ve been to for a science fair?",
    "Have you ever been to a party with a live roller skater?",
    "What’s the most epic party you’ve been to in a forest?",
    "Have you ever been to a party with a live tap dancer?",
    "What’s the best party you’ve been to for a food festival?",
    "Have you ever been to a party with a live hula hooper?",
    "What’s the most memorable party you’ve been to in a factory?",
    "Have you ever been to a party with a live belly dancer?",
    "What’s the best party you’ve been to for a car show?",
    "Have you ever been to a party with a live unicyclist?",
    "What’s the most epic party you’ve been to in a lighthouse?",
    "Have you ever been to a party with a live drag performer?",
    "What’s the best party you’ve been to for a tech event?",
    "Have you ever been to a party with a live yo-yo artist?",
    "What’s the most memorable party you’ve been to in a warehouse?",
    "Have you ever been to a party with a live salsa dancer?",
    "What’s the best party you’ve been to for a dance recital?",
    "Have you ever been to a party with a live skateboarder?",
    "What’s the most epic party you’ve been to in a tunnel?",
    "Have you ever been to a party with a live parkour performer?",
    "What’s the best party you’ve been to for a pet adoption event?",
    "Have you ever been to a party with a live sword dancer?",
    "What’s the most memorable party you’ve been to in a greenhouse?",
    "Have you ever been to a party with a live beatboxer?",
    "What’s the best party you’ve been to for a theater opening?",
    "Have you ever been to a party with a live fire juggler?",
    "What’s the most epic party you’ve been to in a skyscraper?",
    "Have you ever been to a party with a live freestyle rapper?",
    "What’s the best party you’ve been to for a comic book release?",
    "Have you ever been to a party with a live BMX rider?",
    "What’s the most memorable party you’ve been to in a castle ruin?",
    "Have you ever been to a party with a live Bollywood dancer?",
    "What’s the best party you’ve been to for a game night?",
    "Have you ever been to a party with a live slackliner?",
    "What’s the most epic party you’ve been to in a hot air balloon?",
    "Have you ever been to a party with a live capoeira performer?",
    "What’s the best party you’ve been to for a poetry slam?",
    "Have you ever been to a party with a live pole dancer?",
    "What’s the most memorable party you’ve been to in a train station?",
    "Have you ever been to a party with a live harmonica player?",
    "What’s the best party you’ve been to for a craft fair?",
    "Have you ever been to a party with a live acrobatic gymnast?",
    "What’s the most epic party you’ve been to in a treehouse?",
    "Have you ever been to a party with a live violinist?",
    "What’s the best party you’ve been to for a wine tasting?",
    "Have you ever been to a party with a live breakdance crew?",
    "What’s the most memorable party you’ve been to in a subway?",
    "Have you ever been to a party with a live ukulele player?",
    "What’s the best party you’ve been to for a book club?",
    "Have you ever been to a party with a live martial arts demo?",
    "What’s the most epic party you’ve been to in a planetarium?",
    "Have you ever been to a party with a live flute player?",
    "What’s the best party you’ve been to for a chess tournament?",
    "Have you ever been to a party with a live tap dance crew?",
    "What’s the most memorable party you’ve been to in an aquarium?",
    "Have you ever been to a party with a live gospel choir?",
    "What’s the best party you’ve been to for a talent agency?",
    "Have you ever been to a party with a live hula dancer?",
    "What’s the most epic party you’ve been to in a windmill?",
    "Have you ever been to a party with a live banjo player?",
    "What’s the best party you’ve been to for a film festival?",
    "Have you ever been to a party with a live clog dancer?",
    "What’s the most memorable party you’ve been to in a monastery?",
    "Have you ever been to a party with a live accordion player?",
    "What’s the best party you’ve been to for a baking contest?",
    "Have you ever been to a party with a live street performer?",
    "What’s the most epic party you’ve been to in a volcano?",
    "Have you ever been to a party with a live bagpiper?",
    "What’s the best party you’ve been to for a photography exhibit?",
    "Have you ever been to a party with a live Irish step dancer?",
    "What’s the most memorable party you’ve been to in a cave system?",
    "Have you ever been to a party with a live cellist?",
    "What’s the best party you’ve been to for a pottery class?",
    "Have you ever been to a party with a live flamenco dancer?",
    "What’s the most epic party you’ve been to in a glacier?",
    "Have you ever been to a party with a live saxophonist?",
    "What’s the best party you’ve been to for a knitting circle?",
    "Have you ever been to a party with a live tango dancer?",
    "What’s the most memorable party you’ve been to in a cathedral?",
    "Have you ever been to a party with a live trumpeter?",
    "What’s the best party you’ve been to for a magic show?",
    "Have you ever been to a party with a live folk dancer?",
    "What’s the most epic party you’ve been to in a canyon?",
    "Have you ever been to a party with a live harpist?",
    "What’s the best party you’ve been to for a cosplay event?",
    "Have you ever been to a party with a live swing dance crew?",
    "What’s the most memorable party you’ve been to in a lighthouse?",
],


"18+": [
    "What's your wildest bedroom experience?",
    "Have you ever had a one-night stand?",
    "What's the most unexpected place you've gotten frisky?",
    "Have you ever been caught in the act? Spill the tea!",
    "What's the sexiest thing someone has ever whispered to you?",
    "Have you ever faked it to spare someone's feelings?",
    "What's your go-to move to set the mood?",
    "Have you ever had a crush on someone you hooked up with?",
    "What's the most adventurous thing you've tried in bed?",
    "Have you ever sent a spicy text to the wrong person?",
    "What's the longest you've gone without getting intimate?",
    "Have you ever had a 'friends with benefits' situation? How’d it go?",
    "What's the most romantic thing you've done for a partner?",
    "Have you ever been seduced by someone completely unexpected?",
    "What's your biggest turn-on that you’re almost embarrassed to admit?",
    "Have you ever had a dream about someone you shouldn’t have?",
    "What's the most daring place you’ve kissed someone?",
    "Have you ever used a dating app just for hookups?",
    "What's the weirdest food you’ve brought into the bedroom?",
    "Have you ever had a fling while on vacation?",
    "What's the most spontaneous thing you’ve done with a partner?",
    "Have you ever been in love with two people at once?",
    "What's the hottest outfit you’ve worn to impress someone?",
    "Have you ever had a crush confess their feelings in bed?",
    "What's the most memorable kiss you’ve ever had?",
    "Have you ever tried role-playing? What was the vibe?",
    "What's the most awkward thing that’s happened during a hookup?",
    "Have you ever had a partner who was way more experienced than you?",
    "What's the sexiest song that gets you in the mood?",
    "Have you ever had a secret fling no one knows about?",
    "What's the boldest thing you’ve done to get someone’s attention?",
    "Have you ever been in a long-distance steamy situation?",
    "What's the most unexpected compliment you’ve gotten in bed?",
    "Have you ever had a crush on a coworker and acted on it?",
    "What's the most romantic place you’ve gotten intimate?",
    "Have you ever tried something new just to spice things up?",
    "What's the funniest thing that’s happened during a romantic moment?",
    "Have you ever had a partner who was super into PDA?",
    "What's the most creative date that led to something more?",
    "Have you ever had a fling with someone you just met?",
    "What's the hottest thing a partner has done to surprise you?",
    "Have you ever had a moment where the chemistry was instant?",
    "What's the most daring text you’ve ever sent?",
    "Have you ever been in a situation that felt like a movie scene?",
    "What's the most intense eye contact you’ve had during a moment?",
    "Have you ever had a partner who loved to talk dirty?",
    "What's the most unexpected turn-on you’ve discovered about yourself?",
    "Have you ever had a fling that lasted just one wild weekend?",
    "What's the most romantic gesture that led to something steamy?",
    "Have you ever had a partner who was way too loud?",
    "What's the sexiest thing you’ve done to surprise someone?",
    "Have you ever had a crush you never told anyone about?",
    "What's the most spontaneous kiss you’ve ever had?",
    "Have you ever tried a blind date that got spicy?",
    "What's the most memorable place you’ve had a romantic moment?",
    "Have you ever had a partner who loved to tease you?",
    "What's the hottest thing you’ve done on a dare?",
    "Have you ever had a fling with someone from a different country?",
    "What's the most intense moment you’ve had with a stranger?",
    "Have you ever been in a love triangle situation?",
    "What's the sexiest thing you’ve worn to bed?",
    "Have you ever had a partner who was super into surprises?",
    "What's the most romantic thing that happened unexpectedly?",
    "Have you ever had a crush on a friend’s partner?",
    "What's the most daring thing you’ve done on a date?",
    "Have you ever had a moment that felt straight out of a romance novel?",
    "What's the hottest thing someone’s done to flirt with you?",
    "Have you ever had a fling that started with just a look?",
    "What's the most adventurous thing you’ve done to impress someone?",
    "Have you ever had a partner who was super into public affection?",
    "What's the most spontaneous thing you’ve done in a relationship?",
    "Have you ever had a crush you kept secret for years?",
    "What's the sexiest thing you’ve done to get revenge?",
    "Have you ever had a fling that felt like a whirlwind?",
    "What's the most romantic place you’ve kissed someone?",
    "Have you ever tried something spicy just because you were curious?",
    "What's the most awkward thing you’ve said during a moment?",
    "Have you ever had a partner who was super into romance?",
    "What's the hottest thing you’ve done on a whim?",
    "Have you ever had a fling that started at a party?",
    "What's the most intense thing you’ve done to flirt?",
    "Have you ever had a partner who loved to plan steamy nights?",
    "What's the most unexpected place you’ve felt a spark?",
    "Have you ever had a crush on someone you barely knew?",
    "What's the sexiest thing you’ve done to make someone jealous?",
    "Have you ever had a fling that felt like a secret adventure?",
    "What's the most romantic thing you’ve done on a whim?",
    "Have you ever had a partner who was super into spontaneity?",
    "What's the hottest thing you’ve done in the heat of the moment?",
    "Have you ever had a fling that started with a dance?",
    "What's the most daring thing you’ve done to get a kiss?",
    "Have you ever had a partner who loved to push boundaries?",
    "What's the most unexpected thing that turned you on?",
    "Have you ever had a fling that felt like a dream?",
    "What's the most romantic thing you’ve done under the stars?",
    "Have you ever had a partner who was super into flirting?",
    "What's the hottest thing you’ve done to start a spark?",
    "Have you ever had a fling that started with a dare?",
    "What's the most daring thing you’ve done in the name of love?",
    "Have you ever had a partner who loved to keep things spicy?",
    "What's the most unexpected place you’ve had a steamy moment?",
    "Have you ever had a crush that felt totally forbidden?",
    "What's the sexiest thing you’ve done to win someone over?",
    "Have you ever had a fling that felt like a fairy tale?",
    "What's the most romantic thing you’ve done at midnight?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to keep things exciting?",
    "Have you ever had a fling that started with a bet?",
    "What's the most daring thing you’ve done to get someone’s attention?",
    "Have you ever had a partner who loved to break the rules?",
    "What's the most unexpected thing you’ve done in bed?",
    "Have you ever had a crush that you acted on impulsively?",
    "What's the sexiest thing you’ve done to make a moment unforgettable?",
    "Have you ever had a fling that felt like pure magic?",
    "What's the most romantic thing you’ve done in the rain?",
    "Have you ever had a partner who was super into teasing?",
    "What's the hottest thing you’ve done to start a fire?",
    "Have you ever had a fling that started with a glance?",
    "What's the most daring thing you’ve done for a crush?",
    "Have you ever had a partner who loved to keep you guessing?",
    "What's the most unexpected place you’ve felt chemistry?",
    "Have you ever had a crush that felt totally out of reach?",
    "What's the sexiest thing you’ve done to surprise a partner?",
    "Have you ever had a fling that felt like a movie?",
    "What's the most romantic thing you’ve done at sunrise?",
    "Have you ever had a partner who was super into passion?",
    "What's the hottest thing you’ve done to make someone blush?",
    "Have you ever had a fling that started with a joke?",
    "What's the most daring thing you’ve done to spark romance?",
    "Have you ever had a partner who loved to push your buttons?",
    "What's the most unexpected thing that made your heart race?",
    "Have you ever had a crush you confessed to in the moment?",
    "What's the sexiest thing you’ve done to keep the spark alive?",
    "Have you ever had a fling that felt like a secret?",
    "What's the most romantic thing you’ve done on a rooftop?",
    "Have you ever had a partner who was super into adventure?",
    "What's the hottest thing you’ve done to make someone smile?",
    "Have you ever had a fling that started with a spark?",
    "What's the most daring thing you’ve done to get close to someone?",
    "Have you ever had a partner who loved to keep things hot?",
    "What's the most unexpected place you’ve had a kiss?",
    "Have you ever had a crush that felt like a fantasy?",
    "What's the sexiest thing you’ve done to make someone’s day?",
    "Have you ever had a fling that felt like destiny?",
    "What's the most romantic thing you’ve done by candlelight?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to keep things fresh?",
    "Have you ever had a fling that started with a touch?",
    "What's the most daring thing you’ve done to make a move?",
    "Have you ever had a partner who loved to play games?",
    "What's the most unexpected thing that got you in the mood?",
    "Have you ever had a crush you acted on without thinking?",
    "What's the sexiest thing you’ve done to create a moment?",
    "Have you ever had a fling that felt like a thrill?",
    "What's the most romantic thing you’ve done on a beach?",
    "Have you ever had a partner who was super into romance?",
    "What's the hottest thing you’ve done to catch someone’s eye?",
    "Have you ever had a fling that started with a smile?",
    "What's the most daring thing you’ve done to get a reaction?",
    "Have you ever had a partner who loved to keep it spicy?",
    "What's the most unexpected place you’ve felt a connection?",
    "Have you ever had a crush that felt like a dream?",
    "What's the sexiest thing you’ve done to make someone laugh?",
    "Have you ever had a fling that felt like a rollercoaster?",
    "What's the most romantic thing you’ve done in a car?",
    "Have you ever had a partner who was super into flirting?",
    "What's the hottest thing you’ve done to make someone melt?",
    "Have you ever had a fling that started with a conversation?",
    "What's the most daring thing you’ve done to show you care?",
    "Have you ever had a partner who loved to surprise you?",
    "What's the most unexpected thing that made you blush?",
    "Have you ever had a crush you couldn’t resist acting on?",
    "What's the sexiest thing you’ve done to make a night special?",
    "Have you ever had a fling that felt like a whirlwind romance?",
    "What's the most romantic thing you’ve done in a park?",
    "Have you ever had a partner who was super into passion?",
    "What's the hottest thing you’ve done to keep the fire burning?",
    "Have you ever had a fling that started with a challenge?",
    "What's the most daring thing you’ve done to get someone’s number?",
    "Have you ever had a partner who loved to keep things exciting?",
    "What's the most unexpected place you’ve had a moment?",
    "Have you ever had a crush that felt like a secret crush?",
    "What's the sexiest thing you’ve done to make someone swoon?",
    "Have you ever had a fling that felt like a spark?",
    "What's the most romantic thing you’ve done in a hotel?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to make someone’s heart race?",
    "Have you ever had a fling that started with a look?",
    "What's the most daring thing you’ve done to make someone notice you?",
    "Have you ever had a partner who loved to keep it playful?",
    "What's the most unexpected thing that turned you on?",
    "Have you ever had a crush you acted on in the moment?",
    "What's the sexiest thing you’ve done to make a memory?",
    "Have you ever had a fling that felt like a fantasy come true?",
    "What's the most romantic thing you’ve done under the moonlight?",
    "Have you ever had a partner who was super into teasing you?",
    "What's the hottest thing you’ve done to make someone want you?",
    "Have you ever had a fling that started with a kiss?",
    "What's the most daring thing you’ve done to get closer to someone?",
    "Have you ever had a partner who loved to keep things steamy?",
    "What's the most unexpected place you’ve felt a vibe?",
    "Have you ever had a crush that felt like a forbidden fruit?",
    "What's the sexiest thing you’ve done to make someone jealous?",
    "Have you ever had a fling that felt like a wild ride?",
    "What's the most romantic thing you’ve done in a forest?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to make someone blush?",
    "Have you ever had a fling that started with a spark of chemistry?",
    "What's the most daring thing you’ve done to get a date?",
    "Have you ever had a partner who loved to keep things hot?",
    "What's the most unexpected thing that made your heart skip?",
    "Have you ever had a crush you confessed to in a bold way?",
    "What's the sexiest thing you’ve done to make a night unforgettable?",
    "Have you ever had a fling that felt like a summer romance?",
    "What's the most romantic thing you’ve done by a fireplace?",
    "Have you ever had a partner who was super into flirting with you?",
    "What's the hottest thing you’ve done to make someone smile?",
    "Have you ever had a fling that started with a playful bet?",
    "What's the most daring thing you’ve done to spark a connection?",
    "Have you ever had a partner who loved to keep things spicy?",
    "What's the most unexpected place you’ve had a romantic spark?",
    "Have you ever had a crush that felt like a wild dream?",
    "What's the sexiest thing you’ve done to make someone’s night?",
    "Have you ever had a fling that felt like a quick thrill?",
    "What's the most romantic thing you’ve done on a balcony?",
    "Have you ever had a partner who was super into passion?",
    "What's the hottest thing you’ve done to make someone swoon?",
    "Have you ever had a fling that started with a flirty comment?",
    "What's the most daring thing you’ve done to get someone’s attention?",
    "Have you ever had a partner who loved to keep things exciting?",
    "What's the most unexpected thing that got you in the mood?",
    "Have you ever had a crush you acted on without hesitation?",
    "What's the sexiest thing you’ve done to make a moment special?",
    "Have you ever had a fling that felt like a secret romance?",
    "What's the most romantic thing you’ve done in a city?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to make someone’s heart race?",
    "Have you ever had a fling that started with a bold move?",
    "What's the most daring thing you’ve done to get a kiss?",
    "Have you ever had a partner who loved to keep things playful?",
    "What's the most unexpected thing that made you feel a spark?",
    "Have you ever had a crush that felt like a hidden desire?",
    "What's the sexiest thing you’ve done to make someone want you?",
    "Have you ever had a fling that felt like a wild adventure?",
    "What's the most romantic thing you’ve done on a rooftop?",
    "Have you ever had a partner who was super into teasing?",
    "What's the hottest thing you’ve done to make someone melt?",
    "Have you ever had a fling that started with a chance encounter?",
    "What's the most daring thing you’ve done to show your interest?",
    "Have you ever had a partner who loved to keep things steamy?",
    "What's the most unexpected place you’ve had a romantic moment?",
    "Have you ever had a crush that felt like a forbidden spark?",
    "What's the sexiest thing you’ve done to make someone blush?",
    "Have you ever had a fling that felt like a quick romance?",
    "What's the most romantic thing you’ve done in a garden?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to make someone’s day?",
    "Have you ever had a fling that started with a shared secret?",
    "What's the most daring thing you’ve done to get someone’s heart?",
    "Have you ever had a partner who loved to keep things spicy?",
    "What's the most unexpected thing that made you feel alive?",
    "Have you ever had a crush you acted on in a crazy way?",
    "What's the sexiest thing you’ve done to make someone remember you?",
    "Have you ever had a fling that felt like a dream come true?",
    "What's the most romantic thing you’ve done by the ocean?",
    "Have you ever had a partner who was super into passion?",
    "What's the hottest thing you’ve done to make someone’s night?",
    "Have you ever had a fling that started with a flirty game?",
    "What's the most daring thing you’ve done to make someone yours?",
    "Have you ever had a partner who loved to keep things hot?",
    "What's the most unexpected place you’ve felt a connection?",
    "Have you ever had a crush that felt like a wild fantasy?",
    "What's the sexiest thing you’ve done to make someone smile?",
    "Have you ever had a fling that felt like a spark of magic?",
    "What's the most romantic thing you’ve done in a forest?",
    "Have you ever had a partner who was super into surprises?",
    "What's the hottest thing you’ve done to make someone swoon?",
    "Have you ever had a fling that started with a bold flirt?",
    "What's the most daring thing you’ve done to get someone’s love?",
    "Have you ever had a partner who loved to keep things exciting?",
    "What's the most unexpected thing that made your heart race?",
    "Have you ever had a crush you acted on in a wild moment?",
    "What's the sexiest thing you’ve done to make someone yours?",
    "Have you ever had a fling that felt like a secret spark?",
    "What's the most romantic thing you’ve done under the stars?"
]
};

export default truth;